### ISSUE TITLE
make Input component not triggers onChange when input method is composing Chinese character

### ISSUE THREAD

**Issue by ileenhow** [alibaba-fusion/next#35]
**Is your feature request related to a problem? Please describe.**

As we know, input element in React will trigger onChange when a key is pressed. If we are inputting Chinese in it, an input method toolbar will show, and it will composing Chinese words in the toolbar according to what we type, onChange will still be triggered when words are being composed. This won't bother in most situation, but if we need to do something for the input value in real time, for example, validating or autosaving the value, we will get some unwanted chars.

look the example below, when I type `哈哈哈` in input method' bar, the value of input element is `ha'ha'ha`:
```javascript
export class App extends React.Component {
  state = {
    value: ""
  };

  handleChange = e => {
    this.setState({
      value: e.target.value
    });
  };

  render() {
    return (
      <div className="App">
        <p>input value: {this.state.value}</p>
        <input type="text" onChange={this.handleChange} />
      </div>
    );
  }
}
```
![image](https://user-images.githubusercontent.com/8329568/48126394-ee535300-e2bb-11e8-9329-c11a69ff6a37.png)

**Describe the solution you'd like**

vuejs' [v-model](https://cn.vuejs.org/v2/guide/forms.html) directive and [react-composition](https://github.com/onface/react-composition) already support this feature, they both use the native `CompositionEvent` of browser to implement this. So I think Input element of Next should support it as well.

**Describe the API you'd expected**

I think we can keep the current behavior `onChange`, and add another change handler prop, maybe call it `onFinalValueChange` or `onCompositedVauleChange`, so if we want to subscribe value changing only when composition is done, we can use the latter one,  if we want the regular behavior, just use `onChange`. If you think this is okay, I will make a pull request to implement it, looking forward to see your advice~

**Comment by bindoon** [comment]
It seems good. welcome PR.

**Comment by vicerwang** [comment]
A great idea！But we also should notice that using Input in Form, if we offer another onChange property such as `onFinalValueChange` or `onCompositedVauleChange`, in situation of this issue it may be a bit tricky as Form will only use `onChange` property. So is it better to offer an API such as `composition` to determine when to trigger an change event，if it is true，we will receive the real time value in onChange callback，otherwise we will receive the final value，it's default value is true as compatibility.

**Comment by vicerwang** [comment]
@ileenhow Thank you for your reply, it seems that my idea is not working due to the limitations of the react. In addition, if we use Input in the Form, the onChange is actually enough, because whether you click the submit button or enter the return, it will trigger onCompositionEnd first, so we always get the final value of the input. Now i think your solution will work well.

**Comment by bindoon** [comment]
Input can accept the original props to input element.
