### ISSUE TITLE
[Field] 开启parseName 后 setValues 无法对深层次数据赋值

### ISSUE THREAD

**Issue by Mrluobo** [alibaba-fusion/next#497]
related:  https://codepen.io/anon/pen/pYbVrE#anon-login

**Comment by bindoon** [comment]
我已经想到一种解决方法，但是感觉比较hack。  setValues 的时候先把数据缓存下来，等真正init的时候再去处理赋值，getValues 的时候跟着缓存数据去做merge 。
但是要处理的带来的几个问题就是，1. 不清楚何时所有组件init完成，2. 要解决数据赋值后再清空的情况，避免再次赋值 3. 可能要解决数组错位问题

**Comment by bindoon** [comment]
原因：因为开启了parseName 我就认为setValues 里面的 key 是结构化的，这种情况下 dialog里面的form其实还没有初始化出来，所以无法判断真实的key是啥，就赋值不了了。 
临时解决方案：所以用 setValue 替代 setValues 可以解决问题。
```
//        this.field.setValues(nextProps.release);
  for(var i in nextProps.release) {
    this.field.setValue(i, nextProps.release[i]);
  }
```

**Comment by youluna** [comment]
https://riddle.alibaba-inc.com/riddles/f0979d0f when parseName is true, users can't set default value, too.

**Comment by jdkahn** [comment]
The design of the `Field` component is such that the `values` passed to the constructor will be ignored when `parseName` is `true`. This is because it has not initialized the form items yet. I see a few solutions to this issue:
(1) Use the `init` function on the input instead of setting form `values` prop. `{...init('type.a', { initValue: defaultValue.type.a})}`. This requires no change to the library.

(2) Add a function that parses `values` prop and added each to the `field` even if there are no inputs with that name. This will not affect when `parseName` is `false`. Developers will need to be careful to only pass values they wish to use.

@youluna @bindoon What do you think about solution (2)?

**Comment by bindoon** [comment]
>  added each to the field even if there are no inputs with that name

there will be a lot of keys not used. and when people use `getValues` may get extra values.

in my think. when people pass `values` we just store it. when `init` we parse the real value from stored `values`

**Comment by bindoon** [comment]
fixed in PR: https://github.com/alibaba-fusion/next/pull/683
