### ISSUE TITLE
[Form]Form 需要提供能力支持 value 值与内部 field 维护的值相同

### ISSUE THREAD

**Issue by liuyiliuyi** [alibaba-fusion/next#711]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.6

### Component
Form

### Environment
chrome 73

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-panini-s1vp1)

### Steps to reproduce
1. 在定时器结束的时候表单的值应为 note: 'note' 其余的值应为空，而不是 value 与表单显示不同步
2. Form 需要提供能力支持 value 值与内部 field 维护的值相同，而不应该是在接收到新的 value 时内部 调用 setValues 进而只是循环调用 setValue，导致与期望不符
3. 这样会导致 value 与 表单值不同步，以及无法移除字段

**Comment by jdkahn** [comment]
I believe this flow was by design. It allows changing values as inputs are changed without accidentally erasing existing form values. The field is the source of truth.

If you want to clear a form value you can set it to an empty string:
``this.setState({
        value: {
          note: "note",
          username: '',
          password: '',
        }
});``

You could also use the form `reset` function and then you can call `setState` with the new values. 
- `this.form.reset('username')` will clear just the `username`, 
- `this.form.reset(['username', 'password'])` will clear both `username` and `password`,
- `this.form.reset()` will clear all values.
